### PR TITLE
Started with cart-api

### PR DESCRIPTION
**Pull request by egiiiiil**
Co-authored-by: Julia Wos <aliuj22@users.noreply.github.com>
Co-authored-by: Indrajeet Godse <K1-RA@users.noreply.github.com>

### CODE REVIEW

**Review by Hanneslol — APPROVED** [review]
Cool beans

**Review by aliuj22 — APPROVED** [review]
🫡

**Review by K1-RA — DISMISSED** [review]

**Review by fagerblom — COMMENTED** [review]
I don't think it's a good idea to merge before the cart branch is completely finished 🤔

**Review by birkkensen — COMMENTED** [review]
I won't add my vote, but good stuff

**Review by Hanneslol — COMMENTED** [review]
1. Very nice
2.  Cool
3.  Awesome and nice

**Review by aliuj22 — APPROVED** [review]
👌😊🥹👩‍💻🦖

**Review by Hanneslol — APPROVED** [review]

**Review by fagerblom — APPROVED** [review]
Looks fine to me 😊

**Review by birkkensen — APPROVED** [review]
Nice job guys :)

**Pull request merged**
