### PR TITLE
Admin playground

### PR DESCRIPTION
**Pull request by birkkensen**

### CODE REVIEW

**Review by egiiiiil — COMMENTED** [review]
👌

**Review by aliuj22 — APPROVED** [review]
oui oui apprové

**Review by Hanneslol — APPROVED** [review]
GG EZ -1 line of code

**Review by fagerblom — APPROVED** [review]
one thumb for -1 👍

**Review by egiiiiil — APPROVED** [review]

**Review by K1-RA — APPROVED** [review]
https://www.youtube.com/shorts/0QoHrMPaLUs

**Pull request merged**
