### PR TITLE
finnish setup

### PR DESCRIPTION
**Pull request by egiiiiil**

### CODE REVIEW

**Review by birkkensen — APPROVED** [review]
Looks good, don't forget to add the dotenv as the PORT later Egil!

**Review by K1-RA — APPROVED** [review]
https://www.youtube.com/watch?v=LBduNcf1eQc

**Review by aliuj22 — APPROVED** [review]
i guess it will do.

**Review by fagerblom — APPROVED** [review]
no snarky comments

**Review by Hanneslol — COMMENTED** [review]
Such wow very nice

**Pull request merged**
