### PR TITLE
Tdd retro

### PR DESCRIPTION
**Pull request by egiiiiil**

### CODE REVIEW

**Review by K1-RA — APPROVED** [review]
Noice

**Review by aliuj22 — APPROVED** [review]
🫡

**Review by fagerblom — CHANGES_REQUESTED** [review]
Remove line 46-65 of old code, not needed anymore 😉

**Review by birkkensen — CHANGES_REQUESTED** [review]
Great stuff, one little thing - you can remove the commented code from line 45 to 65 in productsController.test.js :)

**Review by birkkensen — APPROVED** [review]
Nice job 👍

**Review by fagerblom — APPROVED** [review]
👾 good job!

**Pull request merged**
